
export const headCells = [
  {
    id: 'original',
    numeric: true,
    disablePadding: true,
    label: 'Original string',
    sortabled: true,
    isSearchable: true,
  },
  {
    id: 'gptTranslation',
    numeric: false,
    disablePadding: false,
    label: 'GPT Translation',
    sortabled: true,
    isSearchable: true,
  },
  {
    id: 'devComment',
    numeric: true,
    disablePadding: false,
    label: 'Dev comment',
    sortabled: true,
    isSearchable: true,
  },
  {
    id: 'stringOwner',
    numeric: true,
    disablePadding: false,
    label: 'String owner',
    sortabled: true,
    isSearchable: true,
  },
  {
    id: 'reviewer',
    numeric: true,
    disablePadding: false,
    sortabled: true,
    label: 'Lasted reviewer',
    isSearchable: true,
  },
  {
    id: 'finalTranslation',
    numeric: true,
    disablePadding: false,
    sortabled: true,
    label: 'Final translation',
    isSearchable: true,
  },
  {
    id: 'status',
    numeric: false,
    disablePadding: false,
    sortabled: true,
    label: 'Status',
    isSearchable: true,
  },
  {
    id: 'actions',
    numeric: false,
    disablePadding: false,
    sortabled: false,
    label: 'Actions',
  },
];